const projects=window.PROJECTS;
const grid=document.querySelector('#projects');const dialog=document.querySelector('#project-dialog');let active='todos';let search='';let lastFocus;
const labels={tiendas:'Tienda online',corporativos:'Sitio corporativo',apps:'App / solución digital'};
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function art(p){return `<div class="plugin-art"><span class="symbol">${p.id.includes('cuotas')?'3×':'✦'}</span><strong>${escape(p.name)}</strong><small>DESARROLLO PARA WOOCOMMERCE</small></div>`}
function openProject(id){let p=projects.find(p=>p.id===id);lastFocus=document.activeElement;document.querySelector('#dialog-title').textContent=p.name;document.querySelector('#dialog-category').textContent=p.sector;document.querySelector('#dialog-description').textContent=p.description;document.querySelector('#dialog-image').innerHTML=p.image?`<img src="${p.image}" alt="Diseño web de ${escape(p.name)}">`:art(p);let link=document.querySelector('#dialog-link');link.hidden=!p.url;if(p.url)link.href=p.url;else link.removeAttribute('href');document.body.classList.add('modal-open');dialog.showModal();document.querySelector('.dialog-scroll').scrollTop=0;document.querySelector('.close').focus()}
function render(){let visible=projects.filter(p=>(active==='todos'||p.category===active)&&normalize(p.name+' '+p.sector+' '+p.description).includes(normalize(search)));grid.innerHTML=visible.map(p=>`<article class="project"><button class="preview" data-project="${p.id}" aria-label="Ver proyecto ${escape(p.name)}"><span class="project-number">${String(projects.indexOf(p)+1).padStart(2,'0')}</span>${p.image?`<div class="browser"><div class="browser-bar"><i></i><i></i><i></i><span>${escape(p.url?new URL(p.url).hostname:p.name)}</span></div><img src="${p.image}" alt="Vista previa del sitio ${escape(p.name)}" loading="lazy" width="1440" height="1100"></div>`:art(p)}<span class="preview-label">Explorar proyecto ↗</span></button><div class="project-meta"><div><h3>${escape(p.name)}</h3><p>${escape(p.sector)}</p></div>${p.url?`<a class="project-link" href="${escape(p.url)}" target="_blank" rel="noopener noreferrer" aria-label="Visitar ${escape(p.name)} (nueva pestaña)">↗</a>`:`<button class="project-link" data-project="${p.id}" aria-label="Ver diseño de ${escape(p.name)}">↗</button>`}</div><span class="project-type">${labels[p.category]}</span></article>`).join('');document.querySelector('.result-count').textContent=`${visible.length} proyecto${visible.length===1?'':'s'} para descubrir`;document.querySelector('.empty').hidden=visible.length!==0;document.querySelectorAll('[data-filter]').forEach(b=>{b.querySelector('sup').textContent=b.dataset.filter==='todos'?projects.length:projects.filter(p=>p.category===b.dataset.filter).length});}
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{active=button.dataset.filter;document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',b===button?'true':'false')});render()}));document.querySelector('input[type="search"]').addEventListener('input',e=>{search=e.target.value;render()});grid.addEventListener('click',e=>{const button=e.target.closest('[data-project]');if(button)openProject(button.dataset.project)});document.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const rect=dialog.getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)dialog.close()}});dialog.addEventListener('close',()=>{document.body.classList.remove('modal-open');lastFocus?.focus()});render();
